### ISSUE TITLE
Python -s option not accepting arguments

### ISSUE THREAD

**Issue by gduffley** [SCIInstitute/SCIRun#1605]
Steps:
1) Call SCIRun -x -s anyscript.py arg1

Result:
[PYTHON] Python 3.4.3 (default, Mar 24 2017, 16:45:03) 
[GCC 4.8.3 20140627 [gcc-4_8-branch revision 212064]] on linux
HEADLESS MODE
2017-03-24 19:35:13.682  [ERROR] File load failed(arg1): exception in load_xml, unrecognized XML syntax

Expected result:
SCIRun runs the script and passes arg1 as an argument.

**Comment by gduffley** [comment]
@dcwhite What's the status of this bug?

**Comment by dcwhite** [comment]
@gduffley This should be fixed. Now everything after the -s flag (except for the script file name) is ignored by SCIRun and available in python via sys.argv. Let me know if there are additional difficulties.

**Comment by gduffley** [comment]
Great, thanks!

**Comment by gduffley** [comment]
If you run:
./SCIRun -x -E -s script.py arg1 arg2
then:
sys.argv = [./SCIRun', '-x', '-E', '-s', 'script.py, 'arg1', 'arg2']

The problem is that if you change which flags you run scirun with, you are going to change the amount of arguments you have. This makes it hard to script. I think that args should be ['script.py, 'arg1', 'arg2'], which is how python would work. The only issue is it makes it so the last scirun flag that you can include is a -s, but I don't think that's terrible design

**Comment by dcwhite** [comment]
Good idea. I will add code to truncate up to and including the -s.

**Comment by gduffley** [comment]
I am still having issues. I am now getting the load file errors that I got before you fixed it. 

Here is the copy and paste from my original bug:

Call SCIRun -x -s anyscript.py arg1

Result:
[PYTHON] Python 3.4.3 (default, Mar 24 2017, 16:45:03)
[GCC 4.8.3 20140627 [gcc-4_8-branch revision 212064]] on linux
HEADLESS MODE
2017-03-24 19:35:13.682 [ERROR] File load failed(arg1): exception in load_xml, unrecognized XML syntax

**Comment by dcwhite** [comment]
What version of SCIRun? Use SCIRun --version

**Comment by dcwhite** [comment]
I ask because I removed the "HEADLESS MODE" print out, so you must be on an old version.

**Comment by gduffley** [comment]
I’m 95% sure I pulled and built that morning. I’m not sure how I would have gone from old version -> new version -> old version again. I’ll test next week when I’m back at SCI.

**Comment by dcwhite** [comment]
Perhaps you did a "git unpull" or "git historical pull" by mistake...

**Comment by gduffley** [comment]
[PYTHON] Python 3.4.3 (default, Jun  2 2017, 11:45:21) 
[GCC 4.8.3 20140627 [gcc-4_8-branch revision 212064]] on linux
v5.0-beta.I-40-geae7f2a

is my version. Don’t worry about this now. I’ll make sure I can reproduce my bug next week.

**Comment by johaenns** [comment]
Any updates on this @dcwhite? I'm still getting this bug with v5.0-beta.S.

**Comment by dcwhite** [comment]
@johaenns Could you make a new bug report with updated details?
